package:
  name: fusioncatcher
  version: "0.99.7b"

source:
  fn: fusioncatcher_v0.99.7b.zip
  url: https://sourceforge.net/projects/fusioncatcher/files/fusioncatcher_v0.99.7b.zip
  sha256: a062fa3b8069c943ccf78e2b2d27f0cc7fcd73b119592ce96c3320653f4ce24b

build:
  number: 0
  skip: True # [not py27]

requirements:
  run:
#      - seqtk-fork ==r82b << this needs to be in first 
      - python
      - numpy
      - biopython
      - xlrd
      - openpyxl
      - bowtie ==1.2.0
      - star ==2.5.2b
      - bowtie2 ==2.3.0
      - blat ==35
      - sra-tools
      - ucsc-liftover ==324
      - bwa
      - pigz

test:
  commands:
      - fusioncatcher.py --help
      - fusioncatcher.py --version

about:
  home: https://github.com/ndaniel/fusioncatcher
  license: GNU General Public License v3 or later (GPLv3+).
  summary: It searches for novel/known somatic fusion genes, translocations, and chimeras in RNA-seq data from diseased samples.
  

