package:
  name: perl-test-simple
  version: "0.98"

source:
  fn: Test-Simple-1.001014.tar.gz
  url: http://search.cpan.org/CPAN/authors/id/E/EX/EXODIST/Test-Simple-1.001014.tar.gz
  #md5: 
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - perl

  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - Test::Builder
    - Test::Builder::IO::Scalar
    - Test::Builder::Module
    - Test::Builder::Tester
    - Test::Builder::Tester::Color
    - Test::Builder::Tester::Tie
    - Test::More
    - Test::Simple
    - Test::Tester
    - Test::Tester::Capture
    - Test::Tester::CaptureRunner
    - Test::Tester::Delegate
    - Test::use::ok

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/Test-More/test-more/
  license: perl_5
  summary: 'Basic utilities for writing tests.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
