package:
    name: "ucsc-gfclient"
    version: "324"
source:
    url: "http://hgdownload.cse.ucsc.edu/admin/exe/userApps.v324.src.tgz"          # [linux]
    fn: "userApps.src.tgz"                                                                     # [linux]
    md5: "c49c168584c5917081d71df854e3cd9d"                                                    # [linux]
    patches:                                                                                   # [linux]
        - "include.patch"                                                                      # [linux]

    url: "http://hgdownload.cse.ucsc.edu/admin/exe/macOSX.x86_64/gfClient"                    # [osx]
    fn: "gfClient"                                                                            # [osx]

build:                                                                                       # [osx]
    script: "mkdir -p $PREFIX/bin; cp gfClient $PREFIX/bin; chmod +x $PREFIX/bin/gfClient" # [osx]

requirements:
    build:
        - libpng                                                    # [linux]
        - mysql                                                     # [linux]
        - zlib                                                      # [linux]
        - openssl                                                   # [linux]
        - gcc

    run:                                                            # [linux]
        - libpng                                                    # [linux]
        - mysql                                                     # [linux]
        - zlib                                                      # [linux]
        - openssl                                                   # [linux]
        - libgcc

test:
    commands:
        # just check for existence, because the individual programs have no unified behavior
        - which gfClient

about:
    home: "http://hgdownload.cse.ucsc.edu/admin/exe/"
    license: "varies; see http://genome.ucsc.edu/license"
    summary: "A client for the genomic finding program that produces a .psl file"
